// Frontend-main/src/pages/BookmarkPage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import PageHeader from '../components/PageHeader.vue'
import { bookmarkAPI, type BookmarkItem } from '../api/bookmark'
import { useAuthStore } from '../store/auth'

const route = useRoute()
const auth = useAuthStore()
const bookmarks = ref<BookmarkItem[]>([])
const error = ref('')

onMounted(async () => {
  await auth.restoreAuth(route.path)
  if (!auth.state.user) {
    error.value = '로그인이 필요한 기능입니다.'
    return
  }

  try {
    const response = await bookmarkAPI.getBookmarkList(auth.state.user.uuid, { page: 1, size: 50, sort: 'created_at', is_asc: false })
    bookmarks.value = response.results
  } catch (fetchError) {
    console.error(fetchError)
    error.value = '북마크를 불러오는데 실패했습니다.'
  }
})
</script>

<template>
  <div class="min-h-screen bg-gray-50 p-10 font-sans">
    <div class="mx-auto max-w-6xl space-y-6">
      <PageHeader title="북마크" subtitle="중요한 개념과 게시물을 한 곳에 모아두고 빠르게 다시 열어보세요." back-link="/" />

      <div v-if="error" class="rounded-3xl border border-red-200 bg-red-50 p-6 text-red-700">{{ error }}</div>

      <section v-else class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        <article
          v-for="item in bookmarks"
          :key="item.uuid ?? item.problem?.uuid ?? `${item.stage}-${item.number}`"
          class="rounded-3xl border-4 border-gray-900 bg-white p-6 shadow-[6px_6px_0_0_rgba(0,0,0,1)]"
        >
          <div class="flex items-center justify-between">
            <h2 class="text-xl font-black text-gray-900">{{ item.problem?.summary ?? `Stage ${item.stage ?? '-'}` }}</h2>
            <span class="text-sm uppercase tracking-[0.2em] text-gray-500">{{ item.type ?? '문제' }}</span>
          </div>
          <p class="mt-4 text-gray-600">문제 번호: {{ item.problem?.number ?? item.number ?? '-' }}</p>
        </article>
      </section>
    </div>
  </div>
</template>

// Frontend-main/src/pages/BookmarkPage.tsx
import PageHeader from '../components/PageHeader';

const BookmarkPage = () => {
  const bookmarks = [
    { id: 1, title: '파이썬 리스트 컴프리헨션', category: '개념 정리' },
    { id: 2, title: '재귀 함수 실전 예제', category: '문제 풀이' },
    { id: 3, title: '효율적인 정렬 알고리즘', category: '강의 요약' },
    { id: 4, title: 'Q&A: 함수형 컴포넌트 상태 관리', category: '커뮤니티' },
  ];

  return (
    <div className="min-h-screen bg-gray-50 p-10 font-sans">
      <div className="max-w-6xl mx-auto space-y-6">
        <PageHeader
          title="북마크"
          subtitle="중요한 개념과 게시물을 한 곳에 모아두고 빠르게 다시 열람하세요."
        />

        <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {bookmarks.map((item) => (
            <div key={item.id} className="rounded-3xl border-4 border-gray-900 bg-white p-6 shadow-[6px_6px_0_0_rgba(0,0,0,1)]">
              <div className="flex items-center justify-between">
                <h2 className="text-xl font-black text-gray-900">{item.title}</h2>
                <span className="text-sm uppercase tracking-[0.2em] text-gray-500">{item.category}</span>
              </div>
              <p className="mt-4 text-gray-600">이 항목은 북마크된 학습 자료로, 언제든지 다시 확인할 수 있습니다.</p>
            </div>
          ))}
        </section>
      </div>
    </div>
  );
};

export default BookmarkPage;
