// Frontend-main/src/pages/CommunityPage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import PageHeader from '../components/PageHeader.vue'
import { communityAnswerAPI, communityPostAPI, type CommunityAnswer, type CommunityPost } from '../api/community'
import { useAuthStore } from '../store/auth'

const router = useRouter()
const route = useRoute()
const auth = useAuthStore()
const questions = ref<CommunityPost[]>([])
const selectedQuestion = ref<CommunityPost | null>(null)
const answers = ref<CommunityAnswer[]>([])
const newQuestionTitle = ref('')
const newQuestionContent = ref('')
const newAnswerContent = ref('')
const isLoading = ref(false)
const showQuestionForm = ref(false)

const displayUser = (user?: { nickname?: string; uuid?: string }) => user?.nickname ?? user?.uuid ?? '익명'

const fetchQuestions = async () => {
  const response = await communityPostAPI.getPostList({ page: 1, size: 50, sort: 'created_at', is_asc: false })
  questions.value = response.results
}

const handleQuestionClick = async (question: CommunityPost) => {
  selectedQuestion.value = await communityPostAPI.getPost(question.uuid)
  const response = await communityAnswerAPI.getAnswerList(question.uuid, { page: 1, size: 50, is_asc: true })
  answers.value = response.results
}

const handleCreateQuestion = async () => {
  isLoading.value = true
  try {
    await communityPostAPI.createPost({ title: newQuestionTitle.value, content: newQuestionContent.value })
    showQuestionForm.value = false
    newQuestionTitle.value = ''
    newQuestionContent.value = ''
    await fetchQuestions()
  } finally {
    isLoading.value = false
  }
}

const handleCreateAnswer = async () => {
  if (!selectedQuestion.value) return
  isLoading.value = true
  try {
    await communityAnswerAPI.createAnswer(selectedQuestion.value.uuid, { content: newAnswerContent.value })
    newAnswerContent.value = ''
    await handleQuestionClick(selectedQuestion.value)
  } finally {
    isLoading.value = false
  }
}

onMounted(async () => {
  await auth.restoreAuth(route.path)
  await fetchQuestions()
})
</script>

<template>
  <div class="min-h-screen bg-[#FFF2EF]">
    <PageHeader
      title="커뮤니티"
      :subtitle="selectedQuestion ? '답변을 읽고 내가 아는 것도 함께 나눠 보세요.' : '궁금한 것을 편하게 물어보고, 다른 친구들의 질문도 구경해 보세요.'"
      :back-link="selectedQuestion ? undefined : '/'"
      @back="selectedQuestion = null"
    >
      <template #rightAction>
        <button
          v-if="!selectedQuestion"
          type="button"
          class="rounded-full bg-[#F7A5A5] px-4 py-2 text-sm font-black text-[#1A2A4F]"
          @click="showQuestionForm = !showQuestionForm"
        >
          질문 쓰기
        </button>
        <button v-else type="button" class="text-sm font-black text-[#1A2A4F]" @click="router.push('/')">
          홈으로
        </button>
      </template>
    </PageHeader>

    <main class="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
      <template v-if="selectedQuestion">
        <div class="rounded-[30px] border border-[#1A2A4F]/10 bg-white p-7 shadow-[0_18px_44px_rgba(26,42,79,0.08)]">
          <div class="inline-flex rounded-full bg-[#FFF2EF] px-4 py-2 text-sm font-bold text-[#1A2A4F]">
            작성자 {{ displayUser(selectedQuestion.user ?? selectedQuestion.member) }}
          </div>
          <h1 class="mt-4 text-3xl font-black text-[#1A2A4F]">{{ selectedQuestion.title }}</h1>
          <p class="mt-4 whitespace-pre-line text-base leading-7 text-slate-700">{{ selectedQuestion.content }}</p>
        </div>

        <div class="mt-6 space-y-4">
          <h2 class="text-2xl font-black text-[#1A2A4F]">답변 {{ answers.length }}개</h2>
          <div v-for="answer in answers" :key="answer.uuid" class="rounded-[28px] border border-[#FFDBB6] bg-white p-5 shadow-[0_14px_30px_rgba(26,42,79,0.06)]">
            <p class="text-sm font-bold text-slate-500">작성자 {{ displayUser(answer.user ?? answer.member) }}</p>
            <p class="mt-3 whitespace-pre-line leading-7 text-slate-700">{{ answer.content }}</p>
          </div>
        </div>

        <div class="mt-6 rounded-[30px] border border-[#F7A5A5] bg-white p-6 shadow-[0_18px_44px_rgba(26,42,79,0.08)]">
          <h3 class="text-xl font-black text-[#1A2A4F]">나도 답변해 보기</h3>
          <textarea
            v-model="newAnswerContent"
            placeholder="친구에게 알려주고 싶은 내용을 편하게 적어 보세요."
            class="mt-4 h-36 w-full resize-none rounded-[22px] border border-[#F7A5A5] bg-[#FFF2EF] p-4 focus:border-[#1A2A4F] focus:outline-none focus:ring-2 focus:ring-[#FFDBB6]"
          />
          <div class="mt-4 flex justify-end">
            <button type="button" :disabled="isLoading" class="rounded-full bg-[#1A2A4F] px-6 py-3 font-black text-[#FFF2EF] hover:bg-[#233868]" @click="handleCreateAnswer">
              답변 등록
            </button>
          </div>
        </div>
      </template>

      <template v-else>
        <div v-if="showQuestionForm" class="mb-6 rounded-[30px] border border-[#F7A5A5] bg-white p-6 shadow-[0_18px_44px_rgba(26,42,79,0.08)]">
          <h2 class="text-2xl font-black text-[#1A2A4F]">새 질문 쓰기</h2>
          <p class="mt-2 text-sm leading-6 text-slate-600">제목은 짧고 분명하게, 내용은 천천히 자세히 적어 보세요.</p>
          <div class="mt-5 space-y-4">
            <input
              v-model="newQuestionTitle"
              type="text"
              placeholder="예: for문이 왜 반복되는지 궁금해요"
              class="w-full rounded-[22px] border border-[#F7A5A5] bg-[#FFF2EF] p-4 focus:border-[#1A2A4F] focus:outline-none focus:ring-2 focus:ring-[#FFDBB6]"
            >
            <textarea
              v-model="newQuestionContent"
              placeholder="어디가 헷갈렸는지, 어떤 걸 해 봤는지 적어 주세요."
              class="h-40 w-full resize-none rounded-[22px] border border-[#F7A5A5] bg-[#FFF2EF] p-4 focus:border-[#1A2A4F] focus:outline-none focus:ring-2 focus:ring-[#FFDBB6]"
            />
            <div class="flex justify-end gap-3">
              <button type="button" class="rounded-full border border-[#1A2A4F] px-5 py-3 font-bold text-[#1A2A4F]" @click="showQuestionForm = false">
                취소
              </button>
              <button type="button" :disabled="isLoading" class="rounded-full bg-[#1A2A4F] px-5 py-3 font-black text-[#FFF2EF]" @click="handleCreateQuestion">
                질문 등록
              </button>
            </div>
          </div>
        </div>

        <div class="grid gap-5">
          <div
            v-for="question in questions"
            :key="question.uuid"
            class="cursor-pointer rounded-[30px] border border-[#1A2A4F]/10 bg-white p-6 shadow-[0_18px_44px_rgba(26,42,79,0.08)] transition hover:-translate-y-1"
            @click="handleQuestionClick(question)"
          >
            <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <p class="inline-flex rounded-full bg-[#FFF2EF] px-3 py-1 text-xs font-bold text-[#1A2A4F]">
                  작성자 {{ displayUser(question.user ?? question.member) }}
                </p>
                <h3 class="mt-3 text-2xl font-black text-[#1A2A4F]">{{ question.title }}</h3>
                <p class="mt-3 line-clamp-3 leading-7 text-slate-600">{{ question.content }}</p>
              </div>
              <div class="rounded-[22px] bg-[#FFDBB6] px-4 py-3 text-center text-sm font-bold text-[#1A2A4F]">
                질문 보기
              </div>
            </div>
          </div>
        </div>
      </template>
    </main>
  </div>
</template>

// Frontend-main/src/pages/CommunityPage.tsx
// src/pages/CommunityPage.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useSelector } from 'react-redux';
import axios from 'axios';
import type { RootState } from '../store';
import PageHeader from '../components/PageHeader';

interface Question {
  uuid: string;
  title: string;
  content: string;
  author: string;
  created_at: string;
  answer_count: number;
  is_answered: boolean;
}

interface Answer {
  uuid: string;
  content: string;
  author: string;
  created_at: string;
}

export default function CommunityPage() {
  const navigate = useNavigate();
  const accessToken = useSelector((state: RootState) => state.auth.accessToken);

  const [questions, setQuestions] = useState<Question[]>([]);
  const [selectedQuestion, setSelectedQuestion] = useState<Question | null>(null);
  const [answers, setAnswers] = useState<Answer[]>([]);
  const [newQuestionTitle, setNewQuestionTitle] = useState('');
  const [newQuestionContent, setNewQuestionContent] = useState('');
  const [newAnswerContent, setNewAnswerContent] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [showQuestionForm, setShowQuestionForm] = useState(false);

  // 질문 목록 불러오기
  useEffect(() => {
    const fetchQuestions = async () => {
      if (!accessToken) return;

      try {
        // API 명세서: GET /api/v1/questions
        const response = await axios.get('/api/v1/questions', {
          headers: { Authorization: `Bearer ${accessToken}` }
        });

        if (response.status === 200) {
          setQuestions(response.data.results);
        }
      } catch (error) {
        console.error('질문 목록을 불러오지 못했습니다:', error);
      }
    };

    fetchQuestions();
  }, [accessToken]);

  // 질문 상세 조회
  const handleQuestionClick = async (question: Question) => {
    setSelectedQuestion(question);
    setNewAnswerContent('');

    try {
      // API 명세서: GET /api/v1/questions/{question_id}
      const response = await axios.get(`/api/v1/questions/${question.uuid}`, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });

      if (response.status === 200) {
        setAnswers(response.data.answers || []);
      }
    } catch (error) {
      console.error('질문 상세를 불러오지 못했습니다:', error);
      alert('질문을 불러오는데 실패했습니다.');
    }
  };

  // 새 질문 작성
  const handleCreateQuestion = async () => {
    if (!newQuestionTitle.trim() || !newQuestionContent.trim()) {
      alert('제목과 내용을 모두 입력해주세요.');
      return;
    }

    setIsLoading(true);
    try {
      // API 명세서: POST /api/v1/questions
      const response = await axios.post('/api/v1/questions', {
        title: newQuestionTitle,
        content: newQuestionContent
      }, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });

      if (response.status === 201) {
        alert('질문이 등록되었습니다!');
        setNewQuestionTitle('');
        setNewQuestionContent('');
        setShowQuestionForm(false);
        // 질문 목록 새로고침
        const questionsResponse = await axios.get('/api/v1/questions', {
          headers: { Authorization: `Bearer ${accessToken}` }
        });
        setQuestions(questionsResponse.data.results);
      }
    } catch (error) {
      console.error('질문 작성 실패:', error);
      alert('질문 작성에 실패했습니다.');
    } finally {
      setIsLoading(false);
    }
  };

  // 답변 작성
  const handleCreateAnswer = async () => {
    if (!newAnswerContent.trim() || !selectedQuestion) return;

    setIsLoading(true);
    try {
      // API 명세서: POST /api/v1/questions/{question_id}/answers
      const response = await axios.post(`/api/v1/questions/${selectedQuestion.uuid}/answers`, {
        content: newAnswerContent
      }, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });

      if (response.status === 201) {
        alert('답변이 등록되었습니다!');
        setNewAnswerContent('');
        // 답변 목록 새로고침
        const questionResponse = await axios.get(`/api/v1/questions/${selectedQuestion.uuid}`, {
          headers: { Authorization: `Bearer ${accessToken}` }
        });
        setAnswers(questionResponse.data.answers || []);
      }
    } catch (error) {
      console.error('답변 작성 실패:', error);
      alert('답변 작성에 실패했습니다.');
    } finally {
      setIsLoading(false);
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('ko-KR', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  if (selectedQuestion) {
    return (
      <div className="min-h-screen bg-gray-50 font-sans">
        <PageHeader
          title="EduQuest 커뮤니티"
          backAction={() => setSelectedQuestion(null)}
          backLabel="질문 목록으로 돌아가기"
          rightAction={
            <button
              onClick={() => navigate('/')}
              className="text-gray-600 hover:text-blue-500 font-bold"
            >
              홈으로
            </button>
          }
        />

        <main className="max-w-4xl mx-auto p-8">
          {/* 질문 상세 */}
          <div className="bg-white p-6 rounded-2xl shadow-md mb-8">
            <h1 className="text-2xl font-bold text-gray-800 mb-4">{selectedQuestion.title}</h1>
            <div className="flex items-center gap-4 text-sm text-gray-500 mb-4">
              <span>작성자: {selectedQuestion.author}</span>
              <span>{formatDate(selectedQuestion.created_at)}</span>
            </div>
            <p className="text-gray-700 whitespace-pre-line">{selectedQuestion.content}</p>
          </div>

          {/* 답변 목록 */}
          <div className="space-y-4 mb-8">
            <h2 className="text-xl font-bold text-gray-800">답변 {answers.length}개</h2>
            {answers.map((answer) => (
              <div key={answer.uuid} className="bg-white p-6 rounded-2xl shadow-md">
                <div className="flex items-center gap-4 text-sm text-gray-500 mb-4">
                  <span>작성자: {answer.author}</span>
                  <span>{formatDate(answer.created_at)}</span>
                </div>
                <p className="text-gray-700 whitespace-pre-line">{answer.content}</p>
              </div>
            ))}
          </div>

          {/* 답변 작성 */}
          <div className="bg-white p-6 rounded-2xl shadow-md">
            <h3 className="text-lg font-bold text-gray-800 mb-4">답변 작성</h3>
            <textarea
              value={newAnswerContent}
              onChange={(e) => setNewAnswerContent(e.target.value)}
              placeholder="답변을 작성해주세요..."
              className="w-full h-32 p-4 border border-gray-300 rounded-lg resize-none focus:outline-none focus:ring-2 focus:ring-[#e8472a]"
            />
            <div className="flex justify-end mt-4">
              <button
                onClick={handleCreateAnswer}
                disabled={isLoading || !newAnswerContent.trim()}
                className="bg-[#e8472a] hover:bg-[#d13d1f] disabled:bg-gray-400 text-white px-6 py-2 rounded-lg font-bold transition-colors"
              >
                {isLoading ? '등록 중...' : '답변 등록'}
              </button>
            </div>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 font-sans">
      <PageHeader
        title="EduQuest 커뮤니티"
        backLink="/"
        rightAction={
          <button
            onClick={() => setShowQuestionForm(!showQuestionForm)}
            className="bg-[#e8472a] hover:bg-[#d13d1f] text-white px-4 py-2 rounded-lg font-bold transition-colors"
          >
            질문 작성
          </button>
        }
      />

      <main className="max-w-4xl mx-auto p-8">
        {/* 질문 작성 폼 */}
        {showQuestionForm && (
          <div className="bg-white p-6 rounded-2xl shadow-md mb-8">
            <h2 className="text-xl font-bold text-gray-800 mb-4">새 질문 작성</h2>
            <div className="space-y-4">
              <input
                type="text"
                value={newQuestionTitle}
                onChange={(e) => setNewQuestionTitle(e.target.value)}
                placeholder="질문 제목을 입력하세요"
                className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#e8472a]"
              />
              <textarea
                value={newQuestionContent}
                onChange={(e) => setNewQuestionContent(e.target.value)}
                placeholder="질문 내용을 자세히 작성해주세요..."
                className="w-full h-40 p-3 border border-gray-300 rounded-lg resize-none focus:outline-none focus:ring-2 focus:ring-[#e8472a]"
              />
              <div className="flex justify-end gap-4">
                <button
                  onClick={() => setShowQuestionForm(false)}
                  className="px-6 py-2 text-gray-600 hover:text-gray-800 font-bold"
                >
                  취소
                </button>
                <button
                  onClick={handleCreateQuestion}
                  disabled={isLoading}
                  className="bg-[#e8472a] hover:bg-[#d13d1f] disabled:bg-gray-400 text-white px-6 py-2 rounded-lg font-bold transition-colors"
                >
                  {isLoading ? '등록 중...' : '질문 등록'}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* 질문 목록 */}
        <div className="space-y-4">
          <h1 className="text-2xl font-bold text-gray-800 mb-6">질문 목록</h1>
          {questions.length === 0 ? (
            <div className="bg-white p-8 rounded-2xl shadow-md text-center">
              <p className="text-gray-500">아직 등록된 질문이 없습니다.</p>
              <p className="text-gray-400 text-sm mt-2">첫 번째 질문을 작성해보세요!</p>
            </div>
          ) : (
            questions.map((question) => (
              <div
                key={question.uuid}
                onClick={() => handleQuestionClick(question)}
                className="bg-white p-6 rounded-2xl shadow-md hover:shadow-lg cursor-pointer transition-shadow"
              >
                <div className="flex justify-between items-start mb-4">
                  <h3 className="text-lg font-bold text-gray-800 hover:text-blue-600 transition-colors">
                    {question.title}
                  </h3>
                  {question.is_answered && (
                    <span className="bg-green-100 text-green-800 px-2 py-1 rounded-full text-xs font-bold">
                      답변완료
                    </span>
                  )}
                </div>
                <p className="text-gray-600 mb-4 line-clamp-2">{question.content}</p>
                <div className="flex justify-between items-center text-sm text-gray-500">
                  <div className="flex gap-4">
                    <span>작성자: {question.author}</span>
                    <span>{formatDate(question.created_at)}</span>
                  </div>
                  <span>답변 {question.answer_count}개</span>
                </div>
              </div>
            ))
          )}
        </div>
      </main>
    </div>
  );
}
