// Frontend-main/src/pages/HomePage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import Navbar from '../components/Navbar.vue'
import { dashboardApi } from '../api/mockApi'
import type { Community, Notice } from '../types/database'

const recentNotices = ref<Notice[]>([])
const recentPosts = ref<Community[]>([])
const userProgress = ref<{ level: number; exp: number; expMax: number; clearedStages: number; totalStages: number } | null>(null)

onMounted(async () => {
  const [notices, posts, progress] = await Promise.all([
    dashboardApi.fetchRecentNotices(),
    dashboardApi.fetchRecentPosts(),
    dashboardApi.fetchUserProgress(),
  ])

  recentNotices.value = notices
  recentPosts.value = posts
  userProgress.value = progress
})
</script>

<template>
  <div class="min-h-screen bg-[#FFF2EF]">
    <Navbar />

    <section class="relative overflow-hidden px-4 pb-10 pt-8 sm:px-6 lg:px-8">
      <div class="absolute left-0 top-10 h-40 w-40 rounded-full bg-[#F7A5A5]/40 blur-3xl" />
      <div class="absolute right-10 top-24 h-48 w-48 rounded-full bg-[#FFDBB6]/60 blur-3xl" />

      <div class="relative mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.2fr_0.8fr]">
        <div class="overflow-hidden rounded-[36px] border-2 border-[#1A2A4F] bg-[#1A2A4F] text-white shadow-[10px_10px_0_0_rgba(26,42,79,0.14)]">
          <div class="grid gap-8 px-6 py-8 sm:px-8 lg:grid-cols-[1fr_0.8fr] lg:items-center">
            <div>
              <p class="inline-flex rounded-full bg-white/15 px-4 py-2 text-sm font-bold text-[#FFDBB6]">
                초등 4학년부터 중학교 2학년까지
              </p>
              <h1 class="mt-5 text-4xl font-black leading-tight sm:text-5xl">
                재미있게 도전하고
                <br />
                천천히 실력을 키워요
              </h1>
              <p class="mt-5 max-w-xl text-base leading-7 text-slate-200 sm:text-lg">
                단계별 스테이지, 오답 노트, 커뮤니티로 혼자서도 배우고 함께 질문할 수 있는 코딩 학습 공간입니다.
              </p>

              <div class="mt-8 flex flex-wrap gap-3">
                <RouterLink
                  to="/game"
                  class="rounded-full border-2 border-white bg-[#F7A5A5] px-6 py-3 text-base font-black text-[#1A2A4F] transition hover:-translate-y-0.5"
                >
                  스테이지 시작하기
                </RouterLink>
                <RouterLink
                  to="/community"
                  class="rounded-full border-2 border-white/50 bg-white/10 px-6 py-3 text-base font-bold text-white transition hover:bg-white/20"
                >
                  질문하러 가기
                </RouterLink>
              </div>
            </div>

            <div class="grid gap-4">
              <div class="rounded-[28px] bg-white p-5 text-[#1A2A4F] shadow-[0_14px_30px_rgba(0,0,0,0.12)]">
                <p class="text-sm font-bold text-slate-500">오늘의 한 줄 목표</p>
                <p class="mt-2 text-xl font-black">하루 한 문제씩 꾸준히!</p>
              </div>
              <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-1">
                <div class="rounded-[28px] bg-[#FFDBB6] p-5 text-[#1A2A4F]">
                  <p class="text-sm font-bold">스테이지 학습</p>
                  <p class="mt-2 text-lg font-black">작은 단계로 차근차근</p>
                </div>
                <div class="rounded-[28px] bg-[#FFF2EF] p-5 text-[#1A2A4F]">
                  <p class="text-sm font-bold">오답 복습</p>
                  <p class="mt-2 text-lg font-black">틀린 문제도 자산으로</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="grid gap-5">
          <div class="rounded-[32px] border border-[#1A2A4F]/10 bg-white p-6 shadow-[0_18px_44px_rgba(26,42,79,0.08)]">
            <p class="text-sm font-bold uppercase tracking-[0.24em] text-[#1A2A4F]/55">학습 현황</p>
            <div v-if="userProgress" class="mt-4 space-y-4">
              <div class="flex items-end justify-between">
                <div>
                  <p class="text-sm text-slate-500">현재 레벨</p>
                  <p class="text-4xl font-black text-[#1A2A4F]">Lv. {{ userProgress.level }}</p>
                </div>
                <RouterLink to="/progress" class="rounded-full bg-[#1A2A4F] px-4 py-2 text-sm font-bold text-white">
                  자세히 보기
                </RouterLink>
              </div>
              <div class="rounded-[24px] bg-[#FFF2EF] p-4">
                <div class="mb-2 flex justify-between text-sm font-bold text-[#1A2A4F]">
                  <span>경험치</span>
                  <span>{{ userProgress.exp }} / {{ userProgress.expMax }}</span>
                </div>
                <div class="h-3 rounded-full bg-white">
                  <div
                    class="h-3 rounded-full bg-[#F7A5A5]"
                    :style="{ width: `${(userProgress.exp / Math.max(userProgress.expMax, 1)) * 100}%` }"
                  />
                </div>
              </div>
              <div class="grid grid-cols-2 gap-4">
                <div class="rounded-[24px] bg-[#FFDBB6] p-4 text-[#1A2A4F]">
                  <p class="text-sm font-bold">클리어 스테이지</p>
                  <p class="mt-2 text-2xl font-black">{{ userProgress.clearedStages }}</p>
                </div>
                <div class="rounded-[24px] bg-[#F7A5A5] p-4 text-[#1A2A4F]">
                  <p class="text-sm font-bold">전체 스테이지</p>
                  <p class="mt-2 text-2xl font-black">{{ userProgress.totalStages }}</p>
                </div>
              </div>
            </div>
          </div>

          <div class="rounded-[32px] border border-[#1A2A4F]/10 bg-white p-6 shadow-[0_18px_44px_rgba(26,42,79,0.08)]">
            <p class="text-sm font-bold uppercase tracking-[0.24em] text-[#1A2A4F]/55">바로 가기</p>
            <div class="mt-4 grid gap-3">
              <RouterLink to="/incorrect-note" class="rounded-[22px] bg-[#FFF2EF] px-5 py-4 font-bold text-[#1A2A4F] transition hover:bg-[#FFDBB6]">
                오답 노트 다시 보기
              </RouterLink>
              <RouterLink to="/community" class="rounded-[22px] bg-[#FFF2EF] px-5 py-4 font-bold text-[#1A2A4F] transition hover:bg-[#F7A5A5]">
                친구들 질문 구경하기
              </RouterLink>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="px-4 pb-14 sm:px-6 lg:px-8">
      <div class="mx-auto grid max-w-7xl gap-6 lg:grid-cols-2">
        <div class="rounded-[32px] border border-[#1A2A4F]/10 bg-white p-6 shadow-[0_18px_44px_rgba(26,42,79,0.08)]">
          <div class="flex items-center justify-between">
            <div>
              <p class="text-sm font-bold uppercase tracking-[0.24em] text-[#1A2A4F]/55">공지사항</p>
              <h2 class="mt-2 text-2xl font-black text-[#1A2A4F]">새 소식을 확인해요</h2>
            </div>
            <RouterLink to="/notice" class="text-sm font-bold text-[#1A2A4F]">더보기</RouterLink>
          </div>
          <div class="mt-5 space-y-3">
            <div
              v-for="notice in recentNotices"
              :key="notice.uuid"
              class="rounded-[24px] border border-[#FFDBB6] bg-[#FFF2EF] p-4"
            >
              <p class="font-bold text-[#1A2A4F]">{{ notice.title }}</p>
              <p class="mt-2 text-sm leading-6 text-slate-600">{{ notice.content.slice(0, 70) }}...</p>
            </div>
          </div>
        </div>

        <div class="rounded-[32px] border border-[#1A2A4F]/10 bg-white p-6 shadow-[0_18px_44px_rgba(26,42,79,0.08)]">
          <div class="flex items-center justify-between">
            <div>
              <p class="text-sm font-bold uppercase tracking-[0.24em] text-[#1A2A4F]/55">커뮤니티</p>
              <h2 class="mt-2 text-2xl font-black text-[#1A2A4F]">친구들과 함께 질문해요</h2>
            </div>
            <RouterLink to="/community" class="text-sm font-bold text-[#1A2A4F]">더보기</RouterLink>
          </div>
          <div class="mt-5 space-y-3">
            <div
              v-for="post in recentPosts"
              :key="post.uuid"
              class="rounded-[24px] border border-[#F7A5A5] bg-white p-4"
            >
              <p class="font-bold text-[#1A2A4F]">{{ post.title }}</p>
              <p class="mt-2 text-sm text-slate-600">
                {{ post.author }} · 답변 {{ post.answers_count ?? 0 }}개
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

// Frontend-main/src/pages/HomePage.tsx
﻿import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import Navbar from '../components/Navbar';
import { dashboardApi } from '../api/mockApi';
import type { Notice, Community } from '../types/database';

interface UserProgress {
  level: number;
  exp: number;
  expMax: number;
  clearedStages: number;
  totalStages: number;
}

export default function HomePage() {
  const [recentNotices, setRecentNotices] = useState<Notice[]>([]);
  const [recentPosts, setRecentPosts] = useState<Community[]>([]);
  const [userProgress, setUserProgress] = useState<UserProgress | null>(null);

  useEffect(() => {
    const loadDashboardData = async () => {
      const [notices, posts, progress] = await Promise.all([
        dashboardApi.fetchRecentNotices(),
        dashboardApi.fetchRecentPosts(),
        dashboardApi.fetchUserProgress(),
      ]);

      setRecentNotices(notices);
      setRecentPosts(posts);
      setUserProgress(progress);
    };

    loadDashboardData();
  }, []);

  return (
    <div className="min-h-screen w-full flex flex-col bg-gray-100 font-mono">
      <Navbar />

      {/* Cinematic Video Section */}
      <div className="relative w-full h-[80vh] overflow-hidden">
        <video
          autoPlay
          loop
          muted
          playsInline
          className="w-full h-full object-cover"
          src="https://www.w3schools.com/html/mov_bbb.mp4"
        />
        <div className="absolute inset-0 bg-black bg-opacity-50 flex items-center justify-center">
          <div className="text-center text-white space-y-6">
            <h1 className="text-6xl font-black">EduQuest: 파이썬 대모험</h1>
            <p className="text-xl max-w-2xl mx-auto">
              알고리즘 학습의 새로운 모험을 시작하세요. 코드의 세계로 떠나보세요!
            </p>
            <Link
              to="/game"
              className="inline-block bg-[#e8472a] text-white px-12 py-6 text-3xl font-black border-4 border-gray-900 shadow-[6px_6px_0_0_rgba(0,0,0,1)] hover:-translate-y-2 transition-transform"
            >
              게임 시작
            </Link>
          </div>
        </div>
      </div>

      {/* Dashboard Content */}
      <div className="flex-1 p-10">
        <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Notices Box */}
          <div className="bg-gray-900 border-4 border-gray-700 rounded-xl p-6 shadow-[8px_8px_0_0_rgba(0,0,0,0.3)]">
            <h2 className="text-2xl font-black text-white mb-4">공지사항</h2>
            <div className="space-y-3">
              {recentNotices.map((notice) => (
                <div key={notice.uuid} className="bg-gray-800 rounded-lg p-3">
                  <h3 className="text-white font-bold text-sm">{notice.title}</h3>
                  <p className="text-gray-400 text-xs mt-1">{notice.content.slice(0, 50)}...</p>
                </div>
              ))}
            </div>
            <Link
              to="/notice"
              className="inline-block mt-4 bg-[#e8472a] text-white px-4 py-2 font-bold border-2 border-gray-700 shadow-[3px_3px_0_0_rgba(0,0,0,1)] hover:-translate-y-1 transition-transform"
            >
              더보기 +
            </Link>
          </div>

          {/* Community Box */}
          <div className="bg-gray-900 border-4 border-gray-700 rounded-xl p-6 shadow-[8px_8px_0_0_rgba(0,0,0,0.3)]">
            <h2 className="text-2xl font-black text-white mb-4">커뮤니티</h2>
            <div className="space-y-3">
              {recentPosts.map((post) => (
                <div key={post.uuid} className="bg-gray-800 rounded-lg p-3">
                  <h3 className="text-white font-bold text-sm">{post.title}</h3>
                  <p className="text-gray-400 text-xs mt-1">by {post.author} • {post.answers_count} 답변</p>
                </div>
              ))}
            </div>
            <Link
              to="/community"
              className="inline-block mt-4 bg-[#e8472a] text-white px-4 py-2 font-bold border-2 border-gray-700 shadow-[3px_3px_0_0_rgba(0,0,0,1)] hover:-translate-y-1 transition-transform"
            >
              더보기 +
            </Link>
          </div>

          {/* Progress Box */}
          <div className="bg-gray-900 border-4 border-gray-700 rounded-xl p-6 shadow-[8px_8px_0_0_rgba(0,0,0,0.3)]">
            <h2 className="text-2xl font-black text-white mb-4">나의 학습현황</h2>
            {userProgress && (
              <div className="space-y-4">
                <div className="text-center">
                  <p className="text-3xl font-black text-[#e8472a]">Lv. {userProgress.level}</p>
                  <p className="text-gray-400 text-sm">현재 레벨</p>
                </div>
                <div>
                  <p className="text-white text-sm mb-2">경험치: {userProgress.exp} / {userProgress.expMax}</p>
                  <div className="w-full bg-gray-700 rounded-full h-3">
                    <div
                      className="bg-[#e8472a] h-3 rounded-full"
                      style={{ width: `${(userProgress.exp / userProgress.expMax) * 100}%` }}
                    />
                  </div>
                </div>
                <div className="text-center">
                  <p className="text-2xl font-black text-white">{userProgress.clearedStages} / {userProgress.totalStages}</p>
                  <p className="text-gray-400 text-sm">클리어한 스테이지</p>
                </div>
              </div>
            )}
            <Link
              to="/progress"
              className="inline-block mt-4 bg-[#e8472a] text-white px-4 py-2 font-bold border-2 border-gray-700 shadow-[3px_3px_0_0_rgba(0,0,0,1)] hover:-translate-y-1 transition-transform"
            >
              더보기 +
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
