// Frontend-main/src/pages/IncorrectNotePage.tsx
import PageHeader from '../components/PageHeader';

const IncorrectNotePage = () => {
  const incorrectNotes = [
    {
      id: 1,
      title: '리스트 인덱스 오류',
      code: 'for i in range(len(arr)+1):\n    print(arr[i])',
      fix: 'for i in range(len(arr)):\n    print(arr[i])',
      reason: '반복 범위가 배열 길이보다 1만큼 더 크게 설정되어 마지막 인덱스를 벗어납니다.',
    },
    {
      id: 2,
      title: '조건문 논리 오류',
      code: 'if x > 0 or x < 10:\n    print("True")',
      fix: 'if x > 0 and x < 10:\n    print("True")',
      reason: 'or를 사용하면 x가 0 이하이거나 10 이상인 경우에도 조건이 참이 됩니다.',
    },
  ];

  return (
    <div className="min-h-screen bg-gray-50 p-10 font-sans">
      <div className="max-w-6xl mx-auto space-y-6">
        <PageHeader
          title="오답노트"
          subtitle="틀렸던 문제와 올바른 해법, 그리고 왜 틀렸는지를 한눈에 확인하세요."
        />

        <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {incorrectNotes.map((note) => (
            <article key={note.id} className="rounded-3xl border-4 border-gray-900 bg-white p-6 shadow-[6px_6px_0_0_rgba(0,0,0,1)]">
              <div className="flex items-center justify-between gap-4">
                <h2 className="text-2xl font-black text-gray-900">{note.title}</h2>
                <span className="text-sm uppercase tracking-[0.3em] text-gray-500">오답 분석</span>
              </div>
              <div className="mt-4 space-y-4">
                <div className="rounded-3xl bg-gray-900 p-4 text-sm text-gray-100 font-mono whitespace-pre-wrap">
                  {note.code}
                </div>
                <div className="rounded-3xl bg-gray-100 p-4 text-sm text-gray-800">
                  <p className="font-bold mb-2">정답 코드</p>
                  <pre className="whitespace-pre-wrap">{note.fix}</pre>
                </div>
                <p className="text-gray-600">이유: {note.reason}</p>
              </div>
            </article>
          ))}
        </section>
      </div>
    </div>
  );
};

export default IncorrectNotePage;

// Frontend-main/src/pages/IncorrectNotePage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import PageHeader from '../components/PageHeader.vue'
import { wrongNoteAPI, type WrongNote } from '../api/wrong_note'
import { useAuthStore } from '../store/auth'

const route = useRoute()
const auth = useAuthStore()
const incorrectNotes = ref<WrongNote[]>([])
const error = ref('')

onMounted(async () => {
  await auth.restoreAuth(route.path)
  if (!auth.state.user) {
    error.value = '로그인이 필요한 기능입니다.'
    return
  }

  try {
    const response = await wrongNoteAPI.getUserWrongNotes(auth.state.user.uuid, {
      page: 0,
      size: 50,
      sort: 'created_at',
      is_asc: false,
    })
    incorrectNotes.value = response.results
  } catch (fetchError) {
    console.error(fetchError)
    error.value = '오답노트를 불러오지 못했습니다.'
  }
})
</script>

<template>
  <div class="min-h-screen bg-[#FFF2EF]">
    <PageHeader
      title="오답노트"
      subtitle="틀린 답안과 AI 피드백을 다시 확인하면서 취약한 부분을 복습해 보세요."
      back-link="/"
    />

    <main class="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
      <div
        v-if="error"
        class="rounded-[28px] border border-[#F7A5A5] bg-white p-6 text-[#1A2A4F] shadow-[0_18px_44px_rgba(26,42,79,0.08)]"
      >
        {{ error }}
      </div>

      <section v-else class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        <article
          v-for="note in incorrectNotes"
          :key="note.uuid"
          class="rounded-[30px] border border-[#1A2A4F]/10 bg-white p-6 shadow-[0_18px_44px_rgba(26,42,79,0.08)]"
        >
          <div class="flex items-center justify-between gap-4">
            <h2 class="text-2xl font-black text-[#1A2A4F]">
              {{ note.problem_id ? `문제 #${note.problem_id}` : '오답 기록' }}
            </h2>
            <span
              class="rounded-full bg-[#FFF2EF] px-3 py-1 text-xs font-black tracking-[0.18em] text-[#1A2A4F]/70"
            >
              {{ note.is_reviewed ? 'REVIEWED' : 'PENDING' }}
            </span>
          </div>
          <div class="mt-4 space-y-4">
            <div class="rounded-[24px] bg-[#1A2A4F] p-4 font-mono text-sm text-gray-100 whitespace-pre-wrap">
              {{ note.wrong_answer }}
            </div>
            <div class="rounded-[24px] bg-[#FFF2EF] p-4 text-sm text-[#1A2A4F]">
              <p class="mb-2 font-black">AI 피드백</p>
              <pre class="whitespace-pre-wrap font-sans">{{
                note.feedback ?? '아직 피드백이 없습니다.'
              }}</pre>
            </div>
            <p class="text-sm leading-6 text-slate-600">
              마지막 제출: {{ note.last_submitted_at ?? note.created_at ?? '-' }}
            </p>
          </div>
        </article>
      </section>
    </main>
  </div>
</template>
