// Frontend-main/src/pages/LoginPage.tsx
// src/pages/LoginPage.tsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { loginSuccess } from '../store/authSlice';
import { authAPI, userAPI } from '../api/auth';
import { decodeJwtUuid } from '../utils/jwt';
import type { RootState } from '../store';

const LoginPage = () => {
  const navigate = useNavigate();
  const dispatch = useDispatch();
  const auth = useSelector((state: RootState) => state.auth);

  const [userId, setUserId] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    if (auth.isAuthReady && auth.isLoggedIn) {
      navigate('/', { replace: true });
    }
  }, [auth.isAuthReady, auth.isLoggedIn, navigate]);

  const handleLogin = async () => {
    setErrorMsg('');
    setIsLoading(true);

    if (!userId || !password) {
      setErrorMsg('아이디와 비밀번호를 모두 입력해주세요! 😡');
      setIsLoading(false);
      return;
    }

    try {
      const response = await authAPI.signIn({ id: userId, password });
      const accessToken = response.accessToken;
      const userUuid = decodeJwtUuid(accessToken);

      if (!userUuid) {
        localStorage.removeItem('accessToken');
        throw new Error('유효하지 않은 토큰입니다.');
      }

      // 프로필 조회 전에 헤더에 토큰을 추가하도록 먼저 저장합니다.
      localStorage.setItem('accessToken', accessToken);

      const profile = await userAPI.getProfile(userUuid);
      const userData = {
        uuid: profile.uuid,
        user_id: profile.user_id,
        nickname: profile.nickname,
        birth: profile.birth,
        role: profile.role,
        is_locked: profile.is_locked,
        balance: profile.wallet?.balance ?? 0
      };

      dispatch(loginSuccess({ user: userData, accessToken }));
      alert('로그인 성공! 대시보드로 이동합니다. 🎮');
      navigate('/');
    } catch (error: any) {
      console.error('로그인 에러:', error);
      localStorage.removeItem('accessToken');
      if (error.response?.status === 400) {
        setErrorMsg('아이디 또는 비밀번호가 일치하지 않습니다! 😢');
      } else if (error.response?.status === 401) {
        setErrorMsg('계정이 잠겨있습니다. 관리자에게 문의하세요.');
      } else {
        setErrorMsg('서버와 연결할 수 없습니다. 잠시 후 다시 시도해주세요.');
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 flex items-center justify-center p-4">
      <div className="bg-white max-w-md w-full p-8 rounded-2xl shadow-xl border border-slate-200 flex flex-col items-center">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-slate-800 mb-2">EduQuest</h1>
          <p className="text-slate-600 text-sm">프로그래밍 학습 플랫폼</p>
        </div>

        {/* 로그인 폼 */}
        <div className="w-full space-y-4 mb-6">
          <div>
            <label className="block text-slate-700 text-sm font-medium mb-2">아이디</label>
            <input
              type="text"
              value={userId}
              onChange={(e) => { setUserId(e.target.value); setErrorMsg(''); }}
              placeholder="아이디를 입력하세요"
              className="w-full px-4 py-3 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
            />
          </div>

          <div>
            <label className="block text-slate-700 text-sm font-medium mb-2">비밀번호</label>
            <div className="relative">
              <input
                type={showPassword ? "text" : "password"}
                value={password}
                onChange={(e) => { setPassword(e.target.value); setErrorMsg(''); }}
                placeholder="비밀번호를 입력하세요"
                className="w-full px-4 py-3 pr-12 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
              />
              <button
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-3.5 text-slate-400 hover:text-slate-600 transition-colors"
              >
                {showPassword ? "🙈" : "👁️"}
              </button>
            </div>
          </div>
        </div>

        {/* 에러 메시지 */}
        {errorMsg && (
          <div className="w-full mb-6 p-3 bg-red-50 border border-red-200 rounded-lg">
            <p className="text-red-600 text-sm text-center">{errorMsg}</p>
          </div>
        )}

        {/* 로그인 버튼 */}
        <button
          onClick={handleLogin}
          disabled={isLoading}
          className="w-full bg-slate-800 hover:bg-slate-700 disabled:bg-slate-400 text-white py-3 px-6 rounded-lg font-medium transition-all duration-200 disabled:cursor-not-allowed mb-4"
        >
          {isLoading ? (
            <div className="flex items-center justify-center">
              <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
              로그인 중...
            </div>
          ) : (
            '로그인'
          )}
        </button>

        {/* 회원가입 링크 */}
        <div className="text-center">
          <span className="text-slate-600 text-sm">계정이 없으신가요? </span>
          <button
            onClick={() => navigate('/signup')}
            className="text-blue-600 hover:text-blue-700 text-sm font-medium transition-colors"
          >
            회원가입
          </button>
        </div>
      </div>
    </div>
  );
};

export default LoginPage;

// Frontend-main/src/pages/LoginPage.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { authAPI, userAPI } from '../api/auth'
import { useAuthStore } from '../store/auth'
import { decodeJwtUuid } from '../utils/jwt'

type LoginFieldKey = 'id' | 'password'

const router = useRouter()
const auth = useAuthStore()
const userId = ref('')
const password = ref('')
const showPassword = ref(false)
const submitError = ref('')
const isLoading = ref(false)
const fieldErrors = ref<Record<LoginFieldKey, string>>({
  id: '',
  password: '',
})

const errorTextClass = 'mt-2 text-sm font-bold text-[#D16A6A]'

const inputClass = (field: LoginFieldKey) =>
  [
    'w-full rounded-[22px] border bg-[#FFF2EF] px-4 py-4 focus:outline-none focus:ring-2',
    fieldErrors.value[field]
      ? 'border-[#D16A6A] ring-2 ring-[#FFD4D4] focus:border-[#D16A6A] focus:ring-[#FFD4D4]'
      : 'border-[#F7A5A5] focus:border-[#1A2A4F] focus:ring-[#FFDBB6]',
  ].join(' ')

watch(
  () => auth.state.isLoggedIn,
  async (loggedIn) => {
    if (auth.state.isAuthReady && loggedIn) {
      await router.replace('/')
    }
  },
  { immediate: true }
)

const resetFieldErrors = () => {
  fieldErrors.value = {
    id: '',
    password: '',
  }
}

const validateForm = () => {
  resetFieldErrors()
  submitError.value = ''

  if (!userId.value.trim()) {
    fieldErrors.value.id = '아이디를 입력해 주세요.'
    return false
  }

  if (!password.value) {
    fieldErrors.value.password = '비밀번호를 입력해 주세요.'
    return false
  }

  return true
}

const clearFieldError = (field: LoginFieldKey) => {
  if (fieldErrors.value[field]) {
    fieldErrors.value[field] = ''
  }
  submitError.value = ''
}

const handleLogin = async () => {
  if (!validateForm()) {
    return
  }

  isLoading.value = true
  submitError.value = ''

  try {
    const response = await authAPI.signIn({ id: userId.value.trim(), password: password.value })
    const accessToken = response.accessToken
    const userUuid =
      decodeJwtUuid(accessToken) ?? (await userAPI.getUuidById(userId.value.trim())).uuid

    if (!userUuid) {
      localStorage.removeItem('accessToken')
      throw new Error('유효하지 않은 토큰입니다.')
    }

    localStorage.setItem('accessToken', accessToken)
    const profile = await userAPI.getProfile(userUuid)

    auth.loginSuccess({
      user: {
        uuid: profile.uuid,
        user_id: profile.user_id ?? profile.id ?? '',
        nickname: profile.nickname,
        birth: profile.birth,
        role: profile.role,
        is_locked: profile.is_locked,
        balance: profile.wallet?.balance ?? profile.point ?? 0,
      },
      accessToken,
    })

    await router.push('/')
  } catch (error: any) {
    console.error('login error:', error)
    localStorage.removeItem('accessToken')
    submitError.value =
      error.response?.data?.details ??
      error.response?.data?.message ??
      '로그인에 실패했습니다. 다시 시도해 주세요.'
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <div class="min-h-screen bg-[linear-gradient(180deg,#fff8f5_0%,#fff2ef_100%)] px-4 py-10">
    <div class="mx-auto flex min-h-[calc(100vh-5rem)] max-w-6xl items-center justify-center">
      <section class="w-full max-w-xl rounded-[36px] border border-[#1A2A4F]/10 bg-white p-8 shadow-[0_18px_44px_rgba(26,42,79,0.08)] sm:p-10">
        <div class="text-center">
          <p class="text-sm font-bold uppercase tracking-[0.24em] text-[#1A2A4F]/55">Welcome Back</p>
          <h2 class="mt-3 text-3xl font-black text-[#1A2A4F]">로그인</h2>
          <p class="mt-2 text-sm leading-6 text-slate-600">
            이어서 학습하려면 계정 정보를 입력해 주세요.
          </p>
        </div>

        <form class="mt-8 space-y-5" novalidate @submit.prevent="handleLogin">
          <div>
            <label class="mb-2 block text-sm font-bold text-[#1A2A4F]">아이디</label>
            <input
              v-model="userId"
              type="text"
              placeholder="아이디를 입력하세요"
              :class="inputClass('id')"
              @input="clearFieldError('id')"
            >
            <p v-if="fieldErrors.id" :class="errorTextClass">{{ fieldErrors.id }}</p>
          </div>

          <div>
            <label class="mb-2 block text-sm font-bold text-[#1A2A4F]">비밀번호</label>
            <div class="relative">
              <input
                v-model="password"
                :type="showPassword ? 'text' : 'password'"
                placeholder="비밀번호를 입력하세요"
                :class="[inputClass('password'), 'pr-20'].join(' ')"
                @input="clearFieldError('password')"
              >
              <button
                type="button"
                class="absolute right-4 top-1/2 -translate-y-1/2 text-sm font-bold text-[#1A2A4F]"
                @click="showPassword = !showPassword"
              >
                {{ showPassword ? '숨기기' : '보기' }}
              </button>
            </div>
            <p v-if="fieldErrors.password" :class="errorTextClass">{{ fieldErrors.password }}</p>
          </div>

          <p v-if="submitError" :class="errorTextClass">{{ submitError }}</p>

          <button
            type="submit"
            :disabled="isLoading"
            class="mt-2 w-full rounded-full bg-[#1A2A4F] px-6 py-4 text-base font-black text-white transition hover:bg-[#233868] disabled:bg-slate-400"
          >
            {{ isLoading ? '로그인 중...' : '학습 이어하기' }}
          </button>
        </form>

        <div class="mt-6 text-center text-sm text-slate-600">
          아직 계정이 없나요?
          <button type="button" class="ml-2 font-bold text-[#1A2A4F]" @click="router.push('/signup')">
            회원가입
          </button>
        </div>
      </section>
    </div>
  </div>
</template>
