// Frontend-main/src/pages/Progress.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useSelector } from 'react-redux';
import type { RootState } from '../store/index';
import { progressApi } from '../api/mockApi';
import type { ProgressStage } from '../api/mockApi';
import PageHeader from '../components/PageHeader';

const Progress = () => {
  const navigate = useNavigate();
  const user = useSelector((state: RootState) => state.auth.user);
  const [stages, setStages] = useState<ProgressStage[]>([]);

  useEffect(() => {
    if (!user) return;

    const fetchAllData = async () => {
      try {
        const progressStages = await progressApi.fetchProgressStages(user.uuid);
        setStages(progressStages);
      } catch (e) {
        console.error('데이터 로드 실패', e);
      }
    };

    fetchAllData();
  }, [user]);

  return (
    <div className="min-h-screen bg-gray-50 p-10 font-sans flex flex-col items-center">
      <div className="w-full max-w-4xl mb-10">
        <PageHeader
          title="학습 현황"
          backLink="/"
        />
      </div>

      <div className="w-full max-w-4xl space-y-4">
        {stages.map((stage) => (
          <div key={stage.uuid} className={`flex items-center justify-between p-6 rounded-3xl border-2 bg-white ${stage.isCleared ? 'border-green-200' : 'border-gray-100'}`}>
            <div className="flex items-center gap-6">
              <div className={`w-12 h-12 rounded-full flex items-center justify-center text-xl font-black ${stage.isCleared ? 'bg-green-500 text-white' : 'bg-gray-200 text-gray-400'}`}>
                {stage.number}
              </div>
              <div>
                <div className="text-xl font-bold text-gray-800">{stage.title}</div>
                <div className="text-sm font-bold text-blue-400">보상: {stage.reward} P</div>
              </div>
            </div>
            
            <div className="flex items-center gap-6">
              <div className="text-right">
                <div className="text-lg font-black text-gray-700">{stage.clearCount} / {stage.totalCount}</div>
                <div className="text-xs font-bold text-gray-400 text-center">CLEAR</div>
              </div>
              <button 
                onClick={() => navigate(`/game?stage=${stage.number}`)}
                className="bg-blue-600 text-white px-8 py-3 rounded-full font-bold hover:bg-blue-500 shadow-md transition-all"
              >
                {stage.isCleared ? '다시하기' : '도전하기'}
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Progress;

// Frontend-main/src/pages/Progress.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import PageHeader from '../components/PageHeader.vue'
import { progressAPI } from '../api/learning'
import { useAuthStore } from '../store/auth'

const router = useRouter()
const route = useRoute()
const auth = useAuthStore()
const stages = ref<{ stage: string | number; total_question_count: number; clear: number[] }[]>([])
const error = ref('')

const normalizedStages = computed(() =>
  stages.value.map((stage) => ({
    uuid: String(stage.stage),
    number: Number(stage.stage),
    title: `Stage ${stage.stage}`,
    reward: '-',
    clearCount: stage.clear.length,
    totalCount: stage.total_question_count,
    isCleared: stage.clear.length === stage.total_question_count && stage.total_question_count > 0,
  }))
)

onMounted(async () => {
  await auth.restoreAuth(route.path)
  if (!auth.state.user) {
    error.value = '로그인이 필요한 기능입니다.'
    return
  }

  try {
    const response = await progressAPI.getProgress(auth.state.user.uuid)
    stages.value = response.results
  } catch {
    error.value = '학습 현황을 불러오지 못했습니다.'
  }
})
</script>

<template>
  <div class="min-h-screen bg-[#FFF2EF]">
    <PageHeader title="학습 현황" subtitle="어디까지 왔는지 보고, 다음 스테이지도 이어서 도전해 보세요." back-link="/" />

    <main class="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
      <div v-if="error" class="rounded-[28px] border border-[#F7A5A5] bg-white p-6 text-[#1A2A4F]">
        {{ error }}
      </div>

      <div v-else class="space-y-5">
        <div class="rounded-[30px] border border-[#1A2A4F]/10 bg-white p-6 shadow-[0_18px_44px_rgba(26,42,79,0.08)]">
          <h2 class="text-2xl font-black text-[#1A2A4F]">한눈에 보는 내 기록</h2>
          <p class="mt-2 text-sm leading-6 text-slate-600">스테이지마다 얼마나 풀었는지 확인하고, 원하는 곳부터 다시 시작할 수 있어요.</p>
        </div>

        <div
          v-for="stage in normalizedStages"
          :key="stage.uuid"
          class="rounded-[30px] border bg-white p-6 shadow-[0_18px_44px_rgba(26,42,79,0.08)]"
          :class="stage.isCleared ? 'border-[#FFDBB6]' : 'border-[#F7A5A5]'"
        >
          <div class="flex flex-col gap-5 md:flex-row md:items-center md:justify-between">
            <div class="flex items-center gap-5">
              <div class="flex h-16 w-16 items-center justify-center rounded-2xl text-2xl font-black" :class="stage.isCleared ? 'bg-[#FFDBB6] text-[#1A2A4F]' : 'bg-[#F7A5A5] text-[#1A2A4F]'">
                {{ stage.number }}
              </div>
              <div>
                <p class="text-2xl font-black text-[#1A2A4F]">{{ stage.title }}</p>
                <p class="mt-1 text-sm text-slate-500">보상: {{ stage.reward }}</p>
              </div>
            </div>

            <div class="flex flex-col gap-4 md:min-w-[260px]">
              <div>
                <div class="mb-2 flex justify-between text-sm font-bold text-[#1A2A4F]">
                  <span>진행률</span>
                  <span>{{ stage.clearCount }} / {{ stage.totalCount }}</span>
                </div>
                <div class="h-3 rounded-full bg-[#FFF2EF]">
                  <div
                    class="h-3 rounded-full bg-[#F7A5A5]"
                    :style="{ width: `${stage.totalCount ? (stage.clearCount / stage.totalCount) * 100 : 0}%` }"
                  />
                </div>
              </div>
              <button
                type="button"
                class="rounded-full bg-[#1A2A4F] px-6 py-3 font-black text-[#FFF2EF] transition hover:bg-[#233868]"
                @click="router.push(`/game?stage=${stage.number}`)"
              >
                {{ stage.isCleared ? '다시 도전하기' : '이어서 풀기' }}
              </button>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</template>
