// Frontend-main/src/pages/Signup.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { authAPI } from '../api/auth'

const router = useRouter()
const isLoading = ref(false)
const errorMsg = ref('')
const profileImage = ref<File | null>(null)
const formData = ref({
  id: '',
  email: '',
  password: '',
  password_confirm: '',
  birth: '',
  nickname: '',
})

const handleFileChange = (event: Event) => {
  profileImage.value = (event.target as HTMLInputElement).files?.[0] ?? null
}

const handleSignup = async () => {
  isLoading.value = true
  errorMsg.value = ''

  try {
    const payload = new FormData()
    payload.append(
      'profile',
      new Blob(
        [
          JSON.stringify({
            id: formData.value.id,
            email: formData.value.email,
            password: formData.value.password,
            password_valid: formData.value.password_confirm,
            birth: formData.value.birth,
            nickname: formData.value.nickname,
          }),
        ],
        { type: 'application/json' }
      )
    )
    if (profileImage.value) {
      payload.append('profileImage', profileImage.value)
    }
    await authAPI.signUp(payload)
    await router.push('/login')
  } catch (error: any) {
    errorMsg.value = error.response?.data?.details ?? error.response?.data?.message ?? '회원가입에 실패했습니다.'
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <div class="min-h-screen bg-[linear-gradient(180deg,#fff8f5_0%,#fff2ef_100%)] px-4 py-10">
    <div class="mx-auto grid min-h-[calc(100vh-5rem)] max-w-6xl items-center gap-8 lg:grid-cols-[0.95fr_1.05fr]">
      <section class="rounded-[36px] border-2 border-[#1A2A4F] bg-white p-8 shadow-[10px_10px_0_0_rgba(26,42,79,0.12)] sm:p-10">
        <p class="text-sm font-bold uppercase tracking-[0.24em] text-[#1A2A4F]/55">회원가입 안내</p>
        <h1 class="mt-3 text-4xl font-black text-[#1A2A4F]">처음 와도 괜찮아요</h1>
        <p class="mt-4 text-base leading-7 text-slate-600">
          계정을 만들면 학습 현황, 오답 노트, 질문 기록을 저장하면서 차근차근 실력을 키울 수 있어요.
        </p>

        <div class="mt-8 grid gap-4">
          <div class="rounded-[28px] bg-[#FFF2EF] p-5">
            <p class="text-sm font-bold text-[#1A2A4F]">이런 점이 좋아요</p>
            <p class="mt-2 text-lg font-black text-[#1A2A4F]">작은 단계로 배우고, 틀린 문제는 다시 복습!</p>
          </div>
          <div class="rounded-[28px] bg-[#FFDBB6] p-5">
            <p class="text-sm font-bold text-[#1A2A4F]">추천 대상</p>
            <p class="mt-2 text-lg font-black text-[#1A2A4F]">초등학교 4학년부터 중학교 2학년까지</p>
          </div>
        </div>
      </section>

      <section class="rounded-[36px] border border-[#1A2A4F]/10 bg-white p-8 shadow-[0_18px_44px_rgba(26,42,79,0.08)] sm:p-10">
        <div class="text-center">
          <p class="text-sm font-bold uppercase tracking-[0.24em] text-[#1A2A4F]/55">Create Account</p>
          <h2 class="mt-3 text-3xl font-black text-[#1A2A4F]">회원가입</h2>
          <p class="mt-2 text-sm leading-6 text-slate-600">아래 정보를 입력하고 학습 모험을 시작해 보세요.</p>
        </div>

        <div v-if="errorMsg" class="mt-5 rounded-[22px] border border-[#F7A5A5] bg-[#FFF2EF] px-4 py-3 text-sm text-[#1A2A4F]">
          {{ errorMsg }}
        </div>

        <form class="mt-6 space-y-4" @submit.prevent="handleSignup">
          <div class="grid gap-4 sm:grid-cols-2">
            <input v-model="formData.id" type="text" placeholder="아이디" class="rounded-[22px] border border-[#F7A5A5] bg-[#FFF2EF] px-4 py-4 focus:border-[#1A2A4F] focus:outline-none focus:ring-2 focus:ring-[#FFDBB6]">
            <input v-model="formData.nickname" type="text" placeholder="닉네임" class="rounded-[22px] border border-[#F7A5A5] bg-[#FFF2EF] px-4 py-4 focus:border-[#1A2A4F] focus:outline-none focus:ring-2 focus:ring-[#FFDBB6]">
          </div>
          <input v-model="formData.email" type="email" placeholder="이메일" class="w-full rounded-[22px] border border-[#F7A5A5] bg-[#FFF2EF] px-4 py-4 focus:border-[#1A2A4F] focus:outline-none focus:ring-2 focus:ring-[#FFDBB6]">
          <div class="grid gap-4 sm:grid-cols-2">
            <input v-model="formData.birth" type="date" class="rounded-[22px] border border-[#F7A5A5] bg-[#FFF2EF] px-4 py-4 focus:border-[#1A2A4F] focus:outline-none focus:ring-2 focus:ring-[#FFDBB6]">
            <input type="file" accept="image/*" class="rounded-[22px] border border-[#F7A5A5] bg-[#FFF2EF] px-4 py-3 text-slate-700 file:mr-3 file:rounded-full file:border-0 file:bg-[#FFDBB6] file:px-4 file:py-2 file:font-bold file:text-[#1A2A4F]" @change="handleFileChange">
          </div>
          <div class="grid gap-4 sm:grid-cols-2">
            <input v-model="formData.password" type="password" placeholder="비밀번호" class="rounded-[22px] border border-[#F7A5A5] bg-[#FFF2EF] px-4 py-4 focus:border-[#1A2A4F] focus:outline-none focus:ring-2 focus:ring-[#FFDBB6]">
            <input v-model="formData.password_confirm" type="password" placeholder="비밀번호 확인" class="rounded-[22px] border border-[#F7A5A5] bg-[#FFF2EF] px-4 py-4 focus:border-[#1A2A4F] focus:outline-none focus:ring-2 focus:ring-[#FFDBB6]">
          </div>

          <button type="submit" :disabled="isLoading" class="mt-4 w-full rounded-full bg-[#1A2A4F] px-6 py-4 text-base font-black text-white transition hover:bg-[#233868] disabled:bg-slate-400">
            {{ isLoading ? '가입 중...' : '회원가입 완료하기' }}
          </button>
        </form>

        <div class="mt-6 text-center text-sm text-slate-600">
          이미 계정이 있나요?
          <button type="button" class="ml-2 font-bold text-[#1A2A4F]" @click="router.push('/login')">로그인</button>
        </div>
      </section>
    </div>
  </div>
</template>

// Frontend-main/src/pages/Signup.tsx
// src/pages/Signup.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { authAPI } from '../api/auth';

const Signup = () => {
  const navigate = useNavigate();
  const [isLoading, setIsLoading] = useState(false);

  const [formData, setFormData] = useState({
    id: '',
    email: '',
    password: '',
    password_confirm: '',
    birth: '',
    nickname: ''
  });
  const [profileImage, setProfileImage] = useState<File | null>(null);

  const [errorMsg, setErrorMsg] = useState('');

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
    setErrorMsg('');
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setProfileImage(e.target.files?.[0] ?? null);
    setErrorMsg('');
  };

  const handleSignup = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    // 유효성 체크
    if (!formData.id || !formData.email || !formData.password || !formData.birth || !formData.nickname) {
      setErrorMsg('모든 정보를 빠짐없이 입력해주세요! 😡');
      return;
    }

    if (formData.password !== formData.password_confirm) {
      setErrorMsg('비밀번호가 서로 다릅니다. 다시 확인해주세요! 🥲');
      return;
    }

    if (formData.password.length < 8) {
      setErrorMsg('비밀번호는 최소 8자 이상이어야 합니다.');
      return;
    }

    if (formData.nickname.length < 3) {
      setErrorMsg('닉네임은 최소 3자 이상이어야 합니다.');
      return;
    }

    setIsLoading(true);

    try {
      const profileData = {
        id: formData.id,
        email: formData.email,
        password: formData.password,
        password_valid: formData.password_confirm,
        birth: formData.birth,
        nickname: formData.nickname
      };

      const payload = new FormData();
      payload.append('profile', new Blob([JSON.stringify(profileData)], { type: 'application/json' }));

      if (profileImage) {
        payload.append('profileImage', profileImage);
      }

      await authAPI.signUp(payload);

      alert('회원가입 성공! 로그인 페이지로 이동합니다. 🎉');
      navigate('/login');
    } catch (error: any) {
      console.error('회원가입 에러:', error);
      if (error.response?.status === 409) {
        setErrorMsg('이미 존재하는 아이디입니다! 다른 아이디를 사용해주세요.');
      } else {
        setErrorMsg('회원가입에 실패했습니다. 다시 시도해주세요.');
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 flex items-center justify-center p-4">
      <div className="bg-white max-w-md w-full p-8 rounded-2xl shadow-xl border border-slate-200 flex flex-col items-center">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-slate-800 mb-2">회원가입</h1>
          <p className="text-slate-600 text-sm">EduQuest에서 프로그래밍을 배워보세요!</p>
        </div>

        {/* 에러 메시지 */}
        {errorMsg && (
          <div className="w-full mb-6 p-3 bg-red-50 border border-red-200 rounded-lg">
            <p className="text-red-600 text-sm text-center">{errorMsg}</p>
          </div>
        )}

        {/* 회원가입 폼 */}
        <form onSubmit={handleSignup} className="w-full space-y-4 mb-6">
          <div>
            <label className="block text-slate-700 text-sm font-medium mb-2">아이디</label>
            <input
              type="text"
              name="id"
              value={formData.id}
              onChange={handleChange}
              placeholder="사용할 아이디를 입력하세요"
              className="w-full px-4 py-3 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
            />
          </div>

          <div>
            <label className="block text-slate-700 text-sm font-medium mb-2">이메일</label>
            <input
              type="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              placeholder="이메일을 입력하세요"
              className="w-full px-4 py-3 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
            />
          </div>

          <div>
            <label className="block text-slate-700 text-sm font-medium mb-2">닉네임</label>
            <input
              type="text"
              name="nickname"
              value={formData.nickname}
              onChange={handleChange}
              placeholder="3자 이상의 닉네임"
              className="w-full px-4 py-3 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
            />
          </div>

          <div>
            <label className="block text-slate-700 text-sm font-medium mb-2">프로필 이미지</label>
            <input
              type="file"
              accept="image/*"
              onChange={handleFileChange}
              className="w-full text-slate-700 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200"
            />
          </div>

          <div>
            <label className="block text-slate-700 text-sm font-medium mb-2">생년월일</label>
            <input
              type="date"
              name="birth"
              value={formData.birth}
              onChange={handleChange}
              className="w-full px-4 py-3 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
            />
          </div>

          <div>
            <label className="block text-slate-700 text-sm font-medium mb-2">비밀번호</label>
            <input
              type="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              placeholder="6자 이상의 비밀번호"
              className="w-full px-4 py-3 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
            />
          </div>

          <div>
            <label className="block text-slate-700 text-sm font-medium mb-2">비밀번호 확인</label>
            <input
              type="password"
              name="password_confirm"
              value={formData.password_confirm}
              onChange={handleChange}
              placeholder="비밀번호를 다시 입력하세요"
              className="w-full px-4 py-3 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
            />
          </div>

          {/* 회원가입 버튼 */}
          <button
            type="submit"
            disabled={isLoading}
            className="w-full bg-slate-800 hover:bg-slate-700 disabled:bg-slate-400 text-white py-3 px-6 rounded-lg font-medium transition-all duration-200 disabled:cursor-not-allowed mt-6"
          >
            {isLoading ? (
              <div className="flex items-center justify-center">
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                가입 중...
              </div>
            ) : (
              '회원가입'
            )}
          </button>
        </form>

        {/* 로그인 링크 */}
        <div className="text-center">
          <span className="text-slate-600 text-sm">이미 계정이 있으신가요? </span>
          <button
            onClick={() => navigate('/login')}
            className="text-blue-600 hover:text-blue-700 text-sm font-medium transition-colors"
          >
            로그인
          </button>
        </div>
      </div>
    </div>
  );
};

export default Signup;
