// Frontend-main/src/components/Navbar.tsx
﻿// src/components/Navbar.tsx
import { useDispatch, useSelector } from 'react-redux';
import { Link, useNavigate } from 'react-router-dom';
import { logout } from '../store/authSlice';
import { authAPI } from '../api/auth';
import type { RootState } from '../store';

export default function Navbar() {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const auth = useSelector((state: RootState) => state.auth);
  const isLoggedIn = auth.isLoggedIn;
  const isAdmin = auth.user?.role === 'admin' || auth.user?.role === 'admine';

  const handleLogout = async () => {
    try {
      await authAPI.logout();
    } catch (error) {
      console.error('로그아웃 API 호출 실패:', error);
    } finally {
      dispatch(logout());
      navigate('/');
    }
  };

  return (
    <nav className="sticky top-0 z-50 w-full bg-[#f5f3f0] border-b-4 border-gray-900">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 font-mono">
        <div className="h-20 flex items-center justify-between">
          <div>
            <span className="text-4xl font-black tracking-tighter text-[#e8472a] uppercase">EDUQUEST</span>
          </div>

          <div className="flex items-center gap-3">
            {!isLoggedIn ? (
              <>
                <Link
                  to="/login"
                  className="bg-white border-2 border-gray-900 shadow-[2px_2px_0_0_rgba(0,0,0,1)] px-4 py-2 font-bold hover:-translate-y-1 transition-transform"
                >
                  로그인
                </Link>
                <Link
                  to="/signup"
                  className="bg-yellow-400 border-2 border-gray-900 shadow-[2px_2px_0_0_rgba(0,0,0,1)] px-4 py-2 font-bold hover:-translate-y-1 transition-transform"
                >
                  회원가입
                </Link>
              </>
            ) : (
              <>
                {isAdmin && (
                  <Link
                    to="/admin"
                    className="bg-yellow-400 border-2 border-gray-900 shadow-[2px_2px_0_0_rgba(0,0,0,1)] px-4 py-2 font-bold hover:-translate-y-1 transition-transform"
                  >
                    관리자
                  </Link>
                )}
                <Link
                  to="/mypage"
                  className="bg-white border-2 border-gray-900 shadow-[2px_2px_0_0_rgba(0,0,0,1)] px-4 py-2 font-bold hover:-translate-y-1 transition-transform"
                >
                  마이페이지
                </Link>
                <button
                  type="button"
                  onClick={handleLogout}
                  className="bg-gray-300 border-2 border-gray-900 shadow-[2px_2px_0_0_rgba(0,0,0,1)] px-4 py-2 font-bold text-gray-800 hover:bg-gray-400 hover:-translate-y-1 transition-transform"
                >
                  로그아웃
                </button>
              </>
            )}
          </div>
        </div>

        <div className="mt-3 flex items-center justify-between border-t border-gray-900/10 pt-4">
          <div className="flex-1" />

          <div className="flex flex-1 justify-center items-center gap-8 text-gray-900 font-bold text-lg">
            <Link to="/stage" className="whitespace-nowrap hover:-translate-y-1 transition-transform">
              스테이지
            </Link>
            <Link to="/progress" className="whitespace-nowrap hover:-translate-y-1 transition-transform">
              학습현황
            </Link>
            <Link to="/incorrect-note" className="whitespace-nowrap hover:-translate-y-1 transition-transform">
              오답노트
            </Link>
            <Link to="/community" className="whitespace-nowrap hover:-translate-y-1 transition-transform">
              커뮤니티
            </Link>
            <Link to="/notice" className="whitespace-nowrap hover:-translate-y-1 transition-transform">
              공지사항
            </Link>
          </div>

          <div className="flex-1 flex justify-end">
            <Link
              to="/game"
              className="rounded-full bg-[#e8472a] px-6 py-2 text-lg font-black text-white border-2 border-gray-900 shadow-[4px_4px_0_0_rgba(0,0,0,1)] hover:-translate-y-1 transition-transform"
            >
              게임시작
            </Link>
          </div>
        </div>
      </div>
    </nav>
  );
}

// Frontend-main/src/components/Navbar.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { authAPI } from '../api/auth'
import { useAuthStore } from '../store/auth'

const router = useRouter()
const auth = useAuthStore()
const isLoggedIn = computed(() => auth.state.isLoggedIn)
const isAdmin = computed(() => {
  const role = auth.state.user?.role
  return role === 'admin' || role === 'admine'
})

const handleLogout = async () => {
  try {
    await authAPI.logout()
  } catch (error) {
    console.error('logout failed:', error)
  } finally {
    auth.logout()
    await router.push('/')
  }
}
</script>

<template>
  <nav class="sticky top-0 z-50 border-b border-[#1A2A4F]/10 bg-white/85 backdrop-blur">
    <div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8">
      <div class="flex flex-col gap-4 lg:grid lg:grid-cols-[1fr_auto_1fr] lg:items-center">
        <div class="flex items-center justify-between gap-4">
          <RouterLink to="/" class="flex items-center gap-3">
            <img src="/logo-transparent.png" alt="EduQuest logo" class="h-12 w-12 object-contain" />
            <div>
              <p class="text-2xl font-black tracking-tight text-[#1A2A4F]">EduQuest</p>
            </div>
          </RouterLink>

          <div class="flex items-center gap-2 lg:hidden">
            <RouterLink
              v-if="!isLoggedIn"
              to="/login"
              class="rounded-full border border-[#1A2A4F] px-4 py-2 text-sm font-bold text-[#1A2A4F]"
            >
              로그인
            </RouterLink>
            <button
              v-else
              type="button"
              class="rounded-full border border-[#1A2A4F] px-4 py-2 text-sm font-bold text-[#1A2A4F]"
              @click="handleLogout"
            >
              로그아웃
            </button>
          </div>
        </div>

        <div class="flex justify-center">
          <div class="flex flex-wrap items-center justify-center gap-2 rounded-[28px] border border-[#1A2A4F]/10 bg-[#FFF2EF] p-2">
            <RouterLink to="/stage" class="rounded-full px-4 py-2 text-sm font-bold text-[#1A2A4F] transition hover:bg-white">
              스테이지
            </RouterLink>
            <RouterLink to="/progress" class="rounded-full px-4 py-2 text-sm font-bold text-[#1A2A4F] transition hover:bg-white">
              학습 현황
            </RouterLink>
            <RouterLink to="/incorrect-note" class="rounded-full px-4 py-2 text-sm font-bold text-[#1A2A4F] transition hover:bg-white">
              오답 노트
            </RouterLink>
            <RouterLink to="/community" class="rounded-full px-4 py-2 text-sm font-bold text-[#1A2A4F] transition hover:bg-white">
              커뮤니티
            </RouterLink>
            <RouterLink to="/notice" class="rounded-full px-4 py-2 text-sm font-bold text-[#1A2A4F] transition hover:bg-white">
              공지사항
            </RouterLink>
          </div>
        </div>

        <div class="hidden justify-end lg:flex">
          <div class="flex items-center gap-2">
            <template v-if="!isLoggedIn">
              <RouterLink
                to="/login"
                class="rounded-full border border-[#1A2A4F] bg-white px-4 py-2 text-sm font-bold text-[#1A2A4F] transition hover:-translate-y-0.5"
              >
                로그인
              </RouterLink>
              <RouterLink
                to="/signup"
                class="rounded-full border border-[#1A2A4F] bg-[#F7A5A5] px-4 py-2 text-sm font-bold text-[#1A2A4F] transition hover:-translate-y-0.5"
              >
                회원가입
              </RouterLink>
            </template>
            <template v-else>
              <RouterLink
                v-if="isAdmin"
                to="/admin"
                class="rounded-full border border-[#1A2A4F] bg-[#FFDBB6] px-4 py-2 text-sm font-bold text-[#1A2A4F]"
              >
                관리자
              </RouterLink>
              <RouterLink
                to="/mypage"
                class="rounded-full border border-[#1A2A4F] bg-white px-4 py-2 text-sm font-bold text-[#1A2A4F]"
              >
                마이페이지
              </RouterLink>
              <button
                type="button"
                class="rounded-full border border-[#1A2A4F] bg-white px-4 py-2 text-sm font-bold text-[#1A2A4F]"
                @click="handleLogout"
              >
                로그아웃
              </button>
            </template>
          </div>
        </div>
      </div>
    </div>
  </nav>
</template>
